### ISSUE TITLE
End of life 31 Jan 2022 ?

### ISSUE THREAD

**Issue by bozhinov** [carbonblack/cbc-zscaler-sandbox-connector#9]
Hello,

https://developer.carbonblack.com/reference/carbon-black-cloud/integrations/zscaler-sandbox-connector/

why ? it is possible to refactor with API v6

Momchil

**Comment by kebringer-cb** [comment]
This integration is no longer being supported. However, information on the deprecated and replacement APIs are on the Developer network if you decide to make the updates.

* [API and Schema Migration Guides](https://developer.carbonblack.com/reference/carbon-black-cloud/api-migration/)

By updating from CBAPI to CBC Python SDK as a dependency, the latest APIs will be used.
* [CBAPI SDK to Carbon Black Cloud Python SDK (CBC SDK) Migration](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/cbapi-sdk-migration/)
